export enum SearchAttributeConstraint {
  actorTerm = "actorTerm",
  genreIndex = "genreIndex",
  artistTerm = "artistTerm",
  shortFilmTerm = "shortFilmTerm",
  producerTerm = "producerTerm",
  ratingTerm = "ratingTerm",
  directorTerm = "directorTerm",
  releaseYearTerm = "releaseYearTerm",
  featureFilmTerm = "featureFilmTerm",
  movieArtistTerm = "movieArtistTerm",
  movieTerm = "movieTerm",
  ratingIndex = "ratingIndex",
  descriptionTerm = "descriptionTerm",
  titleTerm = "titleTerm",
  languageTerm = "languageTerm",
  authorTerm = "authorTerm",
  keywordsTerm = "keywordsTerm",
  mixTerm = "mixTerm",
  composerTerm = "composerTerm",
  softwareDeveloper = "softwareDeveloper",
  tvEpisodeTerm = "tvEpisodeTerm",
  showTerm = "showTerm",
  tvSeasonTerm = "tvSeasonTerm",
  allArtistTerm = "allArtistTerm",
  allTrackTerm = "allTrackTerm",
}
