export enum SearchEntityConstraint {
  movieArtist = "movieArtist",
  movie = "movie",
  podcastAuthor = "podcastAuthor",
  podcast = "podcast",
  musicArtist = "musicArtist",
  musicTrack = "musicTrack",
  album = "album",
  musicVideo = "musicVideo",
  mix = "mix",
  song = "song",
  audioBookAuthor = "audiobookAuthor",
  audioBook = "audiobook",
  shortFilmArtist = "shortFilmArtist",
  shortFilm = "shortFilm",
  tvEpisode = "tvEpisode",
  tvSeason = "tvSeason",
  software = "software",
  iPadSoftware = "iPadSoftware",
  macSoftware = "macSoftware",
  ebook = "ebook",
  allArtist = "allArtist",
  allTrack = "allTrack",
}
